spring:
  application:
    name: jpa-jdbc-paging-test

  datasource:
    url: jdbc:mysql://localhost:3306/batch-test
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always